# Generated by Django 4.2.28 on 2026-02-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(blank=True, default='Independent', max_length=255),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='experience_level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior')], default='Mid', max_length=20),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
